Class sapb1.vo.phoebus.PhoebusTransact Extends %SerialObject
{

Property Nsu As %String;

Property AcquirerNsu As %String;

Property Value As %Integer;

Property RefundedValue As %Integer;

Property Status As %String;

Property Parcels As %Integer;

Property Brand As %String;

Property CardNumber As %String;

Property Aid As %String;

Property StartDate As %String;

Property FinishDate As %String;

Property ConfirmationDate As %String;

Property PaymentCate As %String;

Property ResponseCode As %String;

Property AuthorizationnNumber As %String;

Property Terminal As %String;

Property TerminalSerialNumber As %String;

Property TerminalManufacturer As %String;

Property TerminalModel As %String;

Property TerminalType As %String;

Property Acquirer As %String;

Property Merchant As %String;

Property TefMerchant As %String;

Property StoneCode As %String;

Property MerchantCategoryCode As %String;

Property MerchantNationaltype As %String;

Property MerchantNationalid As %String;

Property ProductName As %String;

Property ProductId As %String;

Property CardInputMethod As %String;

Property RequestedPassword As %String;

Property Fallback As %String;

Property Origin As %String;

Property AuthorizationTime As %String;

Property SimCardSerialNumber As %String;

Property SimCardProvider As %String;

Property CardHolder As %String;

Property CaptureChannel As %String;

Storage Default
{
<Data name="PhoebusTransactState">
<Value name="1">
<Value>Nsu</Value>
</Value>
<Value name="2">
<Value>AcquirerNsu</Value>
</Value>
<Value name="3">
<Value>Value</Value>
</Value>
<Value name="4">
<Value>RefundedValue</Value>
</Value>
<Value name="5">
<Value>Status</Value>
</Value>
<Value name="6">
<Value>Parcels</Value>
</Value>
<Value name="7">
<Value>Brand</Value>
</Value>
<Value name="8">
<Value>CardNumber</Value>
</Value>
<Value name="9">
<Value>Aid</Value>
</Value>
<Value name="10">
<Value>StartDate</Value>
</Value>
<Value name="11">
<Value>FinishDate</Value>
</Value>
<Value name="12">
<Value>ConfirMationDate</Value>
</Value>
<Value name="13">
<Value>PaymentCate</Value>
</Value>
<Value name="14">
<Value>ResponseCode</Value>
</Value>
<Value name="15">
<Value>AuthorizationnNumber</Value>
</Value>
<Value name="16">
<Value>Terminal</Value>
</Value>
<Value name="17">
<Value>TerminalSerialNumber</Value>
</Value>
<Value name="18">
<Value>TerminalManufacturer</Value>
</Value>
<Value name="19">
<Value>TerminalModel</Value>
</Value>
<Value name="20">
<Value>TerminalType</Value>
</Value>
<Value name="21">
<Value>Acquirer</Value>
</Value>
<Value name="22">
<Value>Merchant</Value>
</Value>
<Value name="23">
<Value>TefMerchant</Value>
</Value>
<Value name="24">
<Value>StoneCode</Value>
</Value>
<Value name="25">
<Value>MerchantCategoryCode</Value>
</Value>
<Value name="26">
<Value>MerchantNationaltype</Value>
</Value>
<Value name="27">
<Value>MerchantNationalid</Value>
</Value>
<Value name="28">
<Value>ProductName</Value>
</Value>
<Value name="29">
<Value>ProductId</Value>
</Value>
<Value name="30">
<Value>CardInputMethod</Value>
</Value>
<Value name="31">
<Value>RequestedPassword</Value>
</Value>
<Value name="32">
<Value>Fallback</Value>
</Value>
<Value name="33">
<Value>Origin</Value>
</Value>
<Value name="34">
<Value>AuthorizationTime</Value>
</Value>
<Value name="35">
<Value>SimCardSerialNumber</Value>
</Value>
<Value name="36">
<Value>SimCardProvider</Value>
</Value>
<Value name="37">
<Value>CardHolder</Value>
</Value>
<Value name="38">
<Value>CaptureChannel</Value>
</Value>
<Value name="39">
<Value>ConfirmationDate</Value>
</Value>
</Data>
<State>PhoebusTransactState</State>
<StreamLocation>^sapb1.vo.pD7EC.PhoebusTranFA62S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
